// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_about_statusAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_about_statusAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202208221321330_mig_about_statusAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
